version: "3"
volumes:
  media: null
  pg_data: null
  static: null
services:
  db:
    image: postgres:13.10
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: ./backend/
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/app/media
    entrypoint: [ "/entrypoint.prod.sh" ]
    command: [ "gunicorn", "--bind", "0.0.0.0:9000", "kittygram_backend.wsgi" ]
  frontend:
    build: ./frontend/
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    build: ./nginx/
    depends_on:
      - backend
      - frontend
    volumes:
      - static:/staticfiles
      - media:/app/media
    ports:
      - 9000:80
