version: '3.8'

volumes:
  pg_data:
  static:
  media:


services:
  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file: .env
    restart: always

  backend:
    image: dreamcat18/kittygram_backend:latest
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/app/static
      - media:/app/media
    restart: always

  frontend:
    image: dreamcat18/kittygram_frontend:latest
    volumes:
      - static:/app/build
    restart: always

  gateway:
    image: dreamcat18/kittygram_gateway:latest
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend
      - frontend
    volumes:
      - static:/static
      - media:/media
      - /etc/ssl/certs:/etc/ssl/certs:ro
      - /etc/ssl/private:/etc/ssl/private:ro
    restart: always
