version: '3.8'

volumes:
  pg_data:
  static:
  media:


services:
  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file: .env
    ports:
      - 5432:5432

  backend:
    build: ./backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/app/static
      - media:/app/media
    ports:
      - 8080:8080

  frontend:
    build: ./frontend
    volumes:
      - static:/app/build
    ports:
      - 3000:8080

  gateway:
    build: ./nginx
    ports:
      - 9000:80
    depends_on:
      - backend
      - frontend
    volumes:
      - static:/static
      - media:/media
